### ISSUE TITLE
Floating

### ISSUE THREAD

**Issue by yeknomerif** [gss/engine#103]
How do you do something like floats in CSS? 
http://jsfiddle.net/9LfM3/

How do you avoid overlap on an arbitrary number of items where they each desire to be as top as possible followed by as left as possible giving priority based on child order?

**Comment by Inviz** [comment]
In new gss you can just use floats and bind to computed/intrinsic x/y of those elements.

To avoid overlap with GSS-positioned blocks, you can use cushions, which make the >= constants
