### ISSUE TITLE
Multiplying two variables?

### ISSUE THREAD

**Issue by johanneseckert** [gss/engine#116]
am I right that math involving two variables isn't supported, e.g:

```
  [unit] == 8 !require;
  [factor] == ::window[width] / 200 !require;

  #wrapper {
    width: == [factor] * [unit];
   }
```

**Comment by Hydrotoast** [comment]
@Inviz Is there currently a method for dealing with this? If so, could you please provide a concrete example?

**Comment by Inviz** [comment]
Yes, you can multiply two variables on 2.1.x branch (to be released soon).

Units make one-way binding:

`a == (b * c) px` or `a == b px * c px`.

Cassowary won't directly connect these variable, and will use intermediate external variable instead

**Comment by Hydrotoast** [comment]
Thank you. If I am interpretting your warning correctly, would the following code produce a circular dependency?

```
y == x * x
x == y * y
```

**Comment by Inviz** [comment]
Yes, even simple example would:
`
  y == x px + 1;
  x == y px + 1;
`

or even

`
  x == x px + 1;
`

One-way binding schedules all side effects to be processed in the next tick. It is possible to create a set of expressions that update each other in an endless loop. 

We use this in units, e.g. `n em` generates `n * &computed-font-size`. Probably setting font-size in ems will cause the same issue. 

We could later add some mechanism that supressed cyclic side effects, currently it's a pretty simple logic. We will also have non-linear solver eventually, but it's not the case at the moment.
