### ISSUE TITLE
Conditionals and window resizing break

### ISSUE THREAD

**Issue by Frexuz** [gss/engine#127]
Very simple example:

```
.box {
  height: == 500;
  @if ::window[width] < 800 {
    width: <= 100;
  }
  @else {
    width: <= 200;    
  }
}
```

The "media query" stops to work after resizing the window over the breakpoint a few times.

http://codepen.io/frexuz/pen/raOEjq?editors=100

**Comment by primedirective** [comment]
I notice that media queries and if conditionals that are supposed to match up don't necessarily fire at the same time if scrollbars are displayed onscreen. (http://www.sitepoint.com/rwd-scrollbars-is-chrome-better/) Is this a known issue and can I just use straight up media queries in my GSS to get around it?

**Comment by Inviz** [comment]
Well, it's a "feature" so things that want to be full width wouldnt cause horizontal scrollbar when vertical is there. 

I tried to so separate window width from document width, but it turned out to be tiresome
