### ISSUE TITLE
gss-not-ready class stays in the html css classes

### ISSUE THREAD

**Issue by cbchouinard** [gss/engine#139]
The gss-not-ready class stays in the html classes even after the gss-ready class is added. 

Would it be preferable to remove it once GSS is ready? Do we need it at all?

**Comment by paulyoung** [comment]
The new version of GSS is only concerned with adding and removing the `gss-ready` class, so no need to add `gss-not-ready` to the DOM.

Something equivalent to the following is required:

```html
<style type="text/css">
  html:not(.gss-ready) {
    opacity:0;
  }
</style>
```
```html
<noscript>
  <style type="text/css">
    html:not(.gss-ready) {
      opacity: 1;
    }
  </style>
</noscript>
```

I used `style` tags here to make things concise but it would be much better to replace those with `link` tags to CSS files.
