### ISSUE TITLE
Constraint within ruleset seems to be ignored

### ISSUE THREAD

**Issue by cbchouinard** [gss/engine#140]
I defined a ruleset like this: 

`#compile {
   right: == #ccssout[right];
   width: == 250;
}`

The constaint `right: == #ccssout[right];` seems to be ignored. Check the codepen for an example: 
http://codepen.io/cbchouinard/pen/JoJdya

We've tried with other selector with the same result : `right: == textarea:last[right];`

But the following constraint will be evaluated: `right: == ::window[center-x];`

**Comment by Inviz** [comment]
Selectors are local by default. So #cssout has to be inside #compile for this to work.

To avoid the issue, you gotta use ($ #ccssout)[right]. $(#cssout)[right] will work too, but it's wip

**Comment by paulyoung** [comment]
My preference for not including other selectors within rule sets has prevented me from running into this issue:

```css
#compile[right] == #ccssout[right];

#compile {
  width: == 250;
}
```
