### ISSUE TITLE
Interesting Paper

### ISSUE THREAD

**Issue by mike-thompson-day8** [gss/engine#146]
I hesitate to mention the following,  because (1) you probably already know about it (2) it isn't a practical suggestion right now, but just in case this is unknow to you, I stumbled upon this interesting paper:  http://arxiv.org/pdf/1401.1031v1.pdf

To make it practical, all we'd need is LPSolve cross compiled into JS :-) 

Feel free to close this issue straight off.  Just wasn't sure how else to pass on the link.

**Comment by paulyoung** [comment]
Thanks @mike-thompson-day8 :pray:

We have seen that one, but still good to share!
