### ISSUE TITLE
Explain how to use GSS away from the DOM; e.g. React Native

### ISSUE THREAD

**Issue by subtleGradient** [gss/engine#148]
I'm feeling the urge to make GSS work with React Native.
Please explain to me how I can use GSS in a DOM-less environment.
I'd go figure it out myself, but I don't have that kind of time on my hands these days.

**Comment by neonstalwart** [comment]
i can't say i've read the comments but does #132 help at all?  seems like the same question.

**Comment by Inviz** [comment]
Hey Thomas. I did the last refactoring for you, and your use case. GSS now has two entry points (Engine & Document). Document does all the DOM stuff, units, stylesheets. Engine is pure math, iterators and constants. 

Both Document & Engine operate on three "domains":
- Input - something that processes expressions, e.g. finds elements in case of DOM) and outputs AST for constraints
- Data - observable hash that provides values for gss. In case of Document, its measurements done in bulk, in case of Engine it's constants. Can be updated via `engine.data.merge({a: 123, '$item[x]': 321})`. It is also used to validate values (i.e. that measurements return same result)
- Output - object that applies styles, or values from Data in bulk

**Comment by Inviz** [comment]
So subclass Engine, and its Engine.prototype.Input, Engine.prototype.Data or Engine.prototype.Output.

Check `Document.coffee` to see how this subclass is implemented. 

Adding your own "functions" like units is also straightforward, you need to define a type (e.g. Unit.coffee) and then define functions implementing that type (e.g. px, em). Referring that class by any key in prototype of desired domain makes it recognize your functions. 

So all in all, I suggest checking `document` folder for cuzomisations, it has all the answers!

**Comment by subtleGradient** [comment]
So much awesome! I'm really excited to help make this happen
