### ISSUE TITLE
^ skips rulesets that only have ids

### ISSUE THREAD

**Issue by Inviz** [gss/engine#156]
#button {
       div { ^[x] == 0; } 
    }

selects root instead of button

**Comment by jonnor** [comment]
#mainSection {
    sectionWidth >= 0;

    > div {
        ^[left] == :first[left];
        ^[right] == :last[right];
        left: == :previous[right];
        height: == ($ #mainSection)[height];
    }
}

**Comment by Inviz** [comment]
It was an issue with external stylesheets, that's why we didnt catch it - we dont do that stuff often. I fixed it, but I found another issue https://github.com/gss/engine/issues/157
