### ISSUE TITLE
Trivial usage doesn't work for non-obvious reasons--scopes?

### ISSUE THREAD

**Issue by endash** [gss/engine#164]
So after reading through the guide, I cannot for the life of me figure out why the following doesn't (or at least, shouldn't) work:

    <head>
        <style type="text/gss">
          #one {
            height: == 200;
          }
    
          #two {
            height: == #one[height];
          }
        </style>
    </head>
    <body>
        <div id="one"></div>
        <div id="two"></div>
    </body>

It works if I eliminate the grouping and have them (both) as top-level rules, which would seem to indicate that it's an issue with scopes. It seems a bit crazy, though, not to be able to group rules and still make explicit references to an element. Am I missing something here or is this by design?

**Comment by cbchouinard** [comment]
Hi endash, when using a selector within a ruleset, you're a selecting from descendant element. 

```
#two {
        height: == #one[height];
      }
```
is the equivalent of (#two #one)[height]. You could use the `$` global combinator to select from the root element: 
```
#two {
        height: == ($ #one)[height];
      }
```
For more information check the section "Selectors within rulesets" in our selector guide: http://gridstylesheets.org/guides/selectors

Hope this help, let us know if you need more info.

**Comment by endash** [comment]
OK Thanks. The docs could be clearer IMHO, but as pointed out it does address my problem upon further inspection. At the very least, it's somewhat counterintuitive and maybe warrants a call-out.

**Comment by endash** [comment]
The more times I re-read the section the less unintuitive it seems. Then again, it's hard to "unknow" the answer and see things from the same perspective as before. In hindsight it definitely feels dumb to have missed it :P

**Comment by Inviz** [comment]
Thanks for constructive feedback. We're going to restructure docs and work on some wording. It will be interesting to see your list of pitfalls. 

It was a hard road to this decision of local variables and selectors, but it turned out good. In 2.1 we'll have `$(#selector)` syntax instead of `($ #selector)` available, and will overcome current gotcha making the latter be treated as collection, and not a singular element (causes unintuitive plural binding).
