### ISSUE TITLE
Stylesheets not parsed correctly when linked in HTML

### ISSUE THREAD

**Issue by danieldiekmeier** [gss/engine#173]
When I link to the GSS file with `<link rel="stylesheet" type="text/gss" href="layout.gss"></link>`, it doesn't parse the `^` selector correctly.

I tried to recreate your example: http://codepen.io/thegridgssdocs/pen/JoyMpR

But it only works if I use inline code, and stops working with the exact same code in an external file.

I saw that you only use inline code on your website, is this related to that issue?

**Comment by Inviz** [comment]
You're right. There's a fix on 2.1.x branch.

**Comment by PatrickSCLin** [comment]
when will 2.1.x release ?

this issue killing me so bad lol

**Comment by Inviz** [comment]
Sorry, we're caught up with deadlines. To make a release, we need to update site/bring back CI on document repo, all that stuff we dont have time for now. We're accepting community help.

Just use this source. https://rawgit.com/gss/document/ranges2/dist/gss.document.parser.js That's ranges2 branch serverd directly from github.

**Comment by paulyoung** [comment]
I recommend understanding the [limitations with rawgit](https://rawgit.com/) first or serving it yourself in the meantime.

I think we have some things to figure out about versioning before the next release too.
