### ISSUE TITLE
Are you guys involved with CSS Houdini project?

### ISSUE THREAD

**Issue by Ygg01** [gss/engine#185]
[CSS Houdini](https://wiki.css-houdini.org/) is a project aiming to standardize CSS Object model and if I understand correctly make so custom layout systems can be applied to CSS. I see your project is among the ideas in https://wiki.css-houdini.org/background, but I haven't found any links here.

**Comment by paulyoung** [comment]
We're not involved (as far as I know) :smiley: 

Thanks for the link!

**Comment by Inviz** [comment]
I think GSS is interesting as a low level for your own custom box model. That's what we did on our projects - we don't write GSS source code anymore, but operate on pre-written chunks. It's like CSS, except you can see the "source" code for any property and value.
