### ISSUE TITLE
CCSS and W3C

### ISSUE THREAD

**Issue by renatoi** [gss/engine#192]
I'm really sorry if this has already been asked previously (pretty sure it did) but I couldn't find a direct answer to it.

I was really impressed by Constraint CSS and VFL and even more impressed that there was [a proposal](http://constraints.cs.washington.edu/web/ccss-uwtr.pdf) for this since 1999.

How far has this group or other people have pushed and influenced W3C to actually make it natively supported?

Could we say that concepts of CCSS have been proposed/introduced already but always in the form of conventional CSS? I believe the following specs were developed to address some of the same problems CCSS tries to solve:
- [CSS Grid Layout](http://www.w3.org/TR/css-grid-1/)
- [CSS Flexible Box Layout](http://www.w3.org/TR/css-flexbox-1/)
- [CSS Box Align](http://dev.w3.org/csswg/css-align/)

But they obviously lack a lot of features that CCSS enables due to cyclic references.

Can someone elaborate a little bit more or point me to references of these discussions that are close to how W3C is handling this topic?

**Comment by Inviz** [comment]
I think GSS would be a good language to base standards on, as it's pretty well contained and we've worked hard to make solving process determenistic and (relatively) easy to reason about. But it takes a lot of work to write a proper spec, and there's no incentive from the browser dept. 

In our projects, we take a way of giving up dynamicity for the sake of portability (by exporting pages to css). But it's obviously not suitable for regular websites.
