### ISSUE TITLE
Leaking 'exports' into global

### ISSUE THREAD

**Issue by jstarrdewar** [gss/engine#47]
I believe the offending code is related to the snippet below, but what is happening is that, when including gss as a plain tag in a project that also has amd components, `exports` is getting added to `window` which prevents modules that check for both commonJS and AMD fail if they look for the existence of `exports` as does PIXI.js, for example. (I'm guessing `scope == window` when this runs).

```
// For Node...not that I'm bitter. No no, not at all. Not me. Never...
if (typeof require == "function" &&
    typeof module != "undefined" &&
    typeof load == "undefined") {
  scope.exports = c;
}
// ...well, hardly ever.
```

**Comment by adampilks** [comment]
I put together a very basic pen http://codepen.io/adampilks/pen/vExNZe that show the errors with requirejs.  Requirejs introduces a globals of `require` and `define` which are conflicting with gss.

Is there a way to have these work side by side currently?

**Comment by paulyoung** [comment]
This was addressed in acfae7d2b3ba710f926b0434adea05707592c857 in case that's an option for you until it gets merged to master.

**Comment by paulyoung** [comment]
Actually, the relevant commits are 8334f868da3c524e1f53e9f37fb1cb3a132fccac and 77e1a7e3c888613d4736139bb169cbf4f7a1f1e9 but it's all part of the move to browserify that exists on the `queries` branch.

**Comment by adampilks** [comment]
Great, we are in early development so will point our bower config to that branch for now.

**Comment by paulyoung** [comment]
We tagged `v2.0.0` which includes those commits.
