### ISSUE TITLE
VFL: in-each function

### ISSUE THREAD

**Issue by appsforartists** [gss/engine#73]
I known one of your big points in GSS is source-order independence, but most markup is relational (e.g. sibling nodes should appear adjacent to one another).  Consider the following markup:

    <ul>
        <li>
            <h4>
                Title of something!
            </h4>
            <p>
                More info about something!
            </p>
        </li>
        <li>
            <h4>
                Title of something else!
            </h4>
            <p>
                More info about something else!
            </p>
        </li>
        <li>
            <h4>
                Title of a third thing!
            </h4>
            <p>
                More info about a third thing!
            </p>
        </li>
    </ul>

It would be awesome if I could write something like:

    @v |
       -
       [h4]
       -
       [p]
       -
       |
       
       gap(16)
       in-each(li);

To have it iterate over each `li` and then apply that VFL scoped to just its children.

**Comment by paulyoung** [comment]
```
li {
    @v |-[p]-[h4]-| gap(16);
}
```

**Comment by paulyoung** [comment]
Selectors are now locally scoped by default, so the following would do what you originally requested:

```
li {
    @v |-(h4)-(p)-| gap(16);
}
```
